### ISSUE TITLE
[Bug]: Push notifications on Android do not arrive

### ISSUE THREAD

**Issue by steunobravo** [braze-inc/braze-react-native-sdk#209] opened 2023-04-29 06:42 UTC
### Which Platforms?

Android

### Which React Native Version?

0.70.8

### Which @braze/react-native-sdk SDK version?

4.1.0

### Repro Rate

100%

### Steps To Reproduce

After adding to the Braze project, when from the Tool of Expo notifications (https://expo.dev/Notifications) I try to send a notification on an Android device, the device does not receive the push notification.
If, on the other hand, I remove the Braze dependencies and try to send a notification, the device receives notifications again.

- "@braze/expo-plugin": "^1.1.1"
- "@braze/react-native-sdk": "^4.1.0"

### Expected Behavior

Even after setting braze, notifications must continue to work the same.

### Actual Incorrect Behavior

Android devices do not receive notifications

### Verbose Logs

Braze v24.3.0 .Braze FirebaseMessagingService( 1683): Remote message did not originate from Braze. Not consuming remote message: com.google.firebase.messaging.RemoteMessage

**Comment by radixdev** [comment] 2023-05-01 15:26
1. Can you provide full verbose logs of a reproduction of the issue?
2. Can you provide a link to the Braze push campaign used to test?
3. Are you sending push from Braze directly or from another source?
4. If you need to receive push from non Braze sources as well, you need to follow https://www.braze.com/docs/developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration/#using-your-own-firebase-messaging-service.

**Comment by steunobravo** [comment] 2023-05-02 07:08
I have no other logs in addition to what I shared.
The problem is not the push notifications sent by Braze but my problem is when I try to receive push from non -Braze Sources. I use default FirebaseMessaging.

In fact, I believe that point 4 you indicated me, it could do to my case. But I can't understand where to put the code on Expo. It could be that I have to put it on node_modules/Expo-Notifications/Android/Src/Main/Java/Expo/Modules/Notifications/Service/ExpoFirebaseMessaginvice.kt?

**Comment by radixdev** [comment] 2023-05-03 19:51
Yes, due to how Android manifests route intents, you'd need to override whatever other Firebase Messaging Service is registered in the manifest in order to route Braze specific intents to it.

**Comment by steunobravo** [comment] 2023-05-04 15:43
Ok, I modified expafirebasemessaginivice.kt from:
`package expo.modules.notifications.service

import com.google.firebase.messaging.FirebaseMessagingService
import com.google.firebase.messaging.RemoteMessage
import expo.modules.notifications.service.interfaces.FirebaseMessagingDelegate

open class ExpoFirebaseMessagingService : FirebaseMessagingService() {
  protected open val firebaseMessagingDelegate: FirebaseMessagingDelegate by lazy {
    expo.modules.notifications.service.delegates.FirebaseMessagingDelegate(this)
  }

  override fun onMessageReceived(token: String) = firebaseMessagingDelegate.onMessageReceived(remoteMessage)
  override fun onNewToken(token: String) = firebaseMessagingDelegate.onNewToken(token)
  override fun onDeletedMessages() = firebaseMessagingDelegate.onDeletedMessages()
}
`

to:
`package expo.modules.notifications.service

import com.google.firebase.messaging.FirebaseMessagingService
import com.google.firebase.messaging.RemoteMessage
import expo.modules.notifications.service.interfaces.FirebaseMessagingDelegate
import com.braze.push.BrazeFirebaseMessagingService

open class ExpoFirebaseMessagingService : FirebaseMessagingService() {
  protected open val firebaseMessagingDelegate: FirebaseMessagingDelegate by lazy {
    expo.modules.notifications.service.delegates.FirebaseMessagingDelegate(this)
  }

  override fun onMessageReceived(remoteMessage: RemoteMessage) {
    super.onMessageReceived(remoteMessage)
    if (BrazeFirebaseMessagingService.handleBrazeRemoteMessage(this, remoteMessage)) {
      // This Remote Message originated from Braze and a push notification was displayed.
      // No further action is needed.
    } else {
      // This Remote Message did not originate from Braze.
      // No action was taken and you can safely pass this Remote Message to other handlers.
      firebaseMessagingDelegate.onMessageReceived(remoteMessage)
    }
    
  }
  override fun onNewToken(token: String) = firebaseMessagingDelegate.onNewToken(token)
  override fun onDeletedMessages() = firebaseMessagingDelegate.onDeletedMessages()
}
`

I tried to send a notification from Expo push notifications Tools ([URL](https://expo.dev/notifications)) but I don't receive it.

What am I doing wrong?

**Comment by radixdev** [comment] 2023-05-05 17:23
1. I would add logging and verify that things are being called as you expect. This code looks correct.
2. I would add that logging in this issue to verify
3. I would also ensure that the Braze firebase service isn't still registered in your manifest if you're using another service.

**Comment by ertemishakk** [comment] 2023-05-08 04:58
@steunobravo make sure you're on the latest android version and have added POST_NOTIFICATIONS in your manifest 
https://developer.android.com/develop/ui/views/notifications/notification-permission

**Comment by steunobravo** [comment] 2023-05-15 16:02
Yes I had already POST_NOTIFICATIONS in my manifest:
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="expo.modules.notifications">

  <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
  <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>

  <application>
    <service
      android:name=".service.ExpoFirebaseMessagingService"
      android:exported="false">
      <intent-filter android:priority="-1">
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
      </intent-filter>
    </service>

    <receiver
      android:name=".service.NotificationsService"
      android:enabled="true"
      android:exported="false">
      <intent-filter android:priority="-1">
        <action android:name="expo.modules.notifications.NOTIFICATION_EVENT" />

        <action android:name="android.intent.action.BOOT_COMPLETED" />
        <action android:name="android.intent.action.REBOOT" />
        <action android:name="android.intent.action.QUICKBOOT_POWERON" />
        <action android:name="com.htc.intent.action.QUICKBOOT_POWERON" />

        <action android:name="android.intent.action.MY_PACKAGE_REPLACED" />
      </intent-filter>
    </receiver>

    <service
      android:name="com.braze.push.BrazeFirebaseMessagingService"
      android:exported="false">
      <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
      </intent-filter>
    </service>

    <activity android:name=".service.NotificationForwarderActivity"
      android:theme="@android:style/Theme.Translucent.NoTitleBar"
      android:exported="false"
      android:excludeFromRecents="true"
      android:noHistory="true"
      android:launchMode="standard"
      android:taskAffinity=""
      />
  </application>
</manifest>
`

Is it possible that I need to configure the Braze SDK with a different Firebase project than the one used by Expo?

**Comment by hokstuff** [comment] 2023-09-12 18:18
Since this issue is more directly associated with the Expo plugin, I am closing out this issue as [a dupe of this ticket](https://github.com/braze-inc/braze-expo-plugin/issues/19) in our Expo repo. Please continue to converse on that ticket to ensure that nothing gets lost in the mix - thank you!

**Closed by hokstuff** 2023-09-12 18:18 UTC
Labels: bug
