### ISSUE TITLE
[Bug]: React Native - Seeing both Session Start and Session End at the same time. 

### ISSUE THREAD

**Issue by serkanhekimoglu** [braze-inc/braze-react-native-sdk#207] opened 2023-04-26 12:29 UTC
### Which Platforms?

Both

### Which React Native Version?

0.71.6

### Which @braze/react-native-sdk SDK version?

2.1.0

### Repro Rate

100% of the time

### Steps To Reproduce

Example:
  1. `import Braze from "@braze/react-native-sdk"`.
  2. `Braze.changeUser("id")`
  2. Run the app.

### Expected Behavior

Expecting to see just Session Start event

### Actual Incorrect Behavior

Seeing Session Start and Session End event at the same time
![Screen Shot 2023-04-26 at 15 27 41](https://user-images.githubusercontent.com/6429172/234574465-7fcf106f-ac41-47e2-8888-10f711fc045f.png)

### Additional Information

I should be seeing only Session Start event when I launch application. I have no clue why I am also seeing Session End at the same time without closing or sending app to background.

**Comment by lowip** [comment] 2023-04-26 21:39
Hi @serkanhekimoglu,

This is the expected behavior. When launching the application, the SDK measures how much time has passed since the application was last closed and decides whether to start a new session or continue the existing one.

>  I have no clue why I am also seeing Session End at the same time without closing or sending app to background.

It's not possible for us to send those events when closing or sending the app in the background:
- Your application might be terminated before we successfully sent the event to our servers
- This doesn't follow our _session timeout_ feature / configuration which prevents the creation of sessions when quickly backgrounding the app and re-opening it.

Let me know if you have more questions.

**Closed by lowip** 2023-04-26 21:39 UTC
Labels: bug
